# Generated by Django 5.2.12 on 2026-03-20 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apropos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hero_politique', models.ImageField(blank=True, null=True, upload_to='apropos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'À propos',
                'verbose_name_plural': 'À propos',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('support_tel', models.CharField(blank=True, max_length=100)),
                ('support_email', models.CharField(blank=True, max_length=100)),
                ('support_group_whatsapp', models.CharField(blank=True, max_length=100)),
                ('support_adresse', models.CharField(blank=True, max_length=100)),
                ('reseau_linkedin', models.CharField(blank=True, max_length=100)),
                ('reseau_github', models.CharField(blank=True, max_length=100)),
                ('reseau_facebook', models.CharField(blank=True, max_length=100)),
                ('reseau_youtube', models.CharField(blank=True, max_length=100)),
                ('image_hero_contact', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apropos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='core.apropos')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['ordre', 'annee'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('president', 'Président'), ('vice_president', 'Vice-Président'), ('secretaire', 'Secrétaire'), ('membre', 'Membre'), ('autre', 'Autre')], default='membre', max_length=30)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apropos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.apropos')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
