# Generated by Django 5.2.12 on 2026-03-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caroussel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.ImageField(blank=True, null=True, upload_to='caroussel/bg/', verbose_name='Arrière-plan')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='caroussel/poster/', verbose_name='Affiche')),
                ('actif', models.BooleanField(default=False, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Numéro d'ordre dans le carousel (0 = premier)", verbose_name="Ordre d'affichage")),
                ('date_creat', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousels',
                'ordering': ['ordre', 'date_creat'],
            },
        ),
    ]
