# Generated by Django 5.2.12 on 2026-04-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxeRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name="Libellé de l'axe")),
                ('image', models.ImageField(blank=True, help_text='Image de fond de la carte (recommandé : 800×480 px).', null=True, upload_to='poles/axes/', verbose_name="Image de l'axe")),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Axe de recherche',
                'verbose_name_plural': 'Axes de recherche',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Caroussel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.ImageField(blank=True, null=True, upload_to='caroussel/bg/', verbose_name='Arrière-plan')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='caroussel/poster/', verbose_name='Affiche')),
                ('actif', models.BooleanField(default=False, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Numéro d'ordre dans le carousel (0 = premier)", verbose_name="Ordre d'affichage")),
                ('date_creat', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousels',
                'ordering': ['ordre', 'date_creat'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visuel', models.ImageField(blank=True, null=True, upload_to='mission/visuel/', verbose_name='Visuel')),
                ('label', models.CharField(help_text='Ex : 01 — Recherche', max_length=100, verbose_name='Label')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_reverse', models.BooleanField(default=False, help_text="Affiche l'image à gauche et le texte à droite", verbose_name='Inversé')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans la section Missions", verbose_name='Position')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creat', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['position', 'date_creat'],
            },
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du pôle')),
                ('slug', models.SlugField(blank=True, help_text='Rempli automatiquement à partir du nom.', unique=True)),
                ('description_courte', models.TextField(help_text='Affiché sous le titre dans le bandeau héro.', verbose_name='Description courte (hero)')),
                ('mission', models.TextField(blank=True, verbose_name='Mission (paragraphe principal)')),
                ('mission_detail', models.TextField(blank=True, verbose_name='Mission (paragraphe complémentaire)')),
                ('image_hero', models.ImageField(blank=True, help_text='Grande image de fond du bandeau héro (recommandé : 1920×700 px).', null=True, upload_to='poles/hero/', verbose_name='Image héro')),
                ('image_mission', models.ImageField(blank=True, help_text='Image affichée à côté du texte de mission (recommandé : 800×600 px).', null=True, upload_to='poles/mission/', verbose_name='Image de la section Mission')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif (visible sur le site)')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('axes', models.ManyToManyField(blank=True, related_name='poles', to='core.axerecherche', verbose_name='Axes de recherche')),
                ('membres', models.ManyToManyField(blank=True, related_name='poles', to='core.profile', verbose_name='Membres du pôle')),
            ],
            options={
                'verbose_name': 'Pôle',
                'verbose_name_plural': 'Pôles',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
