# Generated by Django 5.2.12 on 2026-03-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_caroussel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visuel', models.ImageField(blank=True, null=True, upload_to='mission/visuel/', verbose_name='Visuel')),
                ('label', models.CharField(help_text='Ex : 01 — Recherche', max_length=100, verbose_name='Label')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_reverse', models.BooleanField(default=False, help_text="Affiche l'image à gauche et le texte à droite", verbose_name='Inversé')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans la section Missions", verbose_name='Position')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creat', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['position', 'date_creat'],
            },
        ),
    ]
