# Generated by Django 5.2.12 on 2026-04-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_axerecherche_caroussel_mission_pole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("presidente", "Présidente Fondatrice"),
                    ("directeur", "Directeur Programmes"),
                    ("resp_rd", "Resp. Pôle R&D"),
                    ("assistant_resp_rd", "Assistant Resp. Pôle R&D"),
                    ("resp_formation", "Resp. Pôle Formation"),
                    ("assistant_resp_formation", "Assistant Resp. Pôle Formation"),
                    ("resp_com", "Resp. Pôle Communication"),
                    ("assistant_resp_com", "Assistant Resp. Pôle Communication"),
                    ("resp_technique", "Resp. Pôle Technique"),
                    ("assistant_resp_technique", "Assistant Resp. Pôle Technique"),
                    ("secretaire", "Secrétaire Générale"),
                    ("resp_finance", "Resp. Finance"),
                    ("resp_conformite", "Resp. Conformité"),
                    ("membre", "Membre"),
                    ("autre", "Autre"),
                ],
                default="membre",
                max_length=30,
            ),
        ),
    ]
