# Generated by Django 5.2.12 on 2026-03-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='label',
            field=models.CharField(choices=[('right', 'right'), ('left', 'left')], default='right'),
        ),
    ]
