# Generated by Django 5.2.12 on 2026-04-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="support_chaine_whatsapp",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
