# Generated by Django 5.2.12 on 2026-03-21 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_evenement_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='label',
        ),
    ]
