# Generated by Django 5.2.12 on 2026-04-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_contact_support_chaine_whatsapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="support_chaine_whatsapp",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
