# Generated by Django 5.2.12 on 2026-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_contact_support_chaine_whatsapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="reseau_facebook",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="reseau_github",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="reseau_linkedin",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="reseau_youtube",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
