# Generated by Django 5.2.12 on 2026-04-21 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('event_date',), 'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AlterModelOptions(
            name='heroarticle',
            options={'ordering': ('-published_at',), 'verbose_name': 'Article à la une', 'verbose_name_plural': 'Articles à la une'},
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ('-published_at',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='image',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='reading_time',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='heroarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='heroarticle',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, to='actualite.tag'),
        ),
    ]
